music = {
    "hindi songs": "https://youtu.be/NX5yDs_TLqA?si=I_UTYcrhEhO7muJc",
    "aarti sangani": "https://youtu.be/CpS1RAZKUXc?si=F8yCQ0uRgSrNB3Cp",
    "falguni pathak": "https://youtu.be/6x7OAy_N5XA?si=ycyh3ahN0ISbyWem",
    "kinjal dave": "https://youtu.be/BPbbBR0X2GY?si=zz9kzYbxTvVsxuW9",
    "geeta rabari": "https://youtu.be/3oVxFSbatCM?si=DCuJH5sMEO0dTFi3",
    "anupsinh": "https://youtu.be/Zs8sU9HJWeo?si=WJn6HRjjDlsuHhBi",
    "sagardan gadhvi": "https://youtu.be/SBpfgOnuG38?si=xFOtIGU8jqElZCnm",
    "mayabhai ahir": "https://youtu.be/5BtasyujGfs?si=O_LF_zxpqYgakbS5",
    "paras pandhi": "https://youtu.be/Z49d4c53Jrw?si=HYNKt9k1tlE1SwWC",
    "devayat khavad": "https://youtu.be/aNZHth9OeBU?si=y6JJVBBH3t6wrRpF",
    "sairam dave": "https://youtu.be/ArEL24CAaVg?si=EMqCYvvQtpV8tpeq",
    "dhirubhai sarvaiya": "https://youtu.be/fsI8ULJwDsw?si=OM2qeBWmUjFA1PwV",
    "narendra modi": "https://youtu.be/YFar3Iv30KA?si=A4AZqFk4QO3PNd7p",
    "amit shah": "https://www.youtube.com/live/0NdfOJHiCJU?si=jc68OemQY5ayqtd2",
    "jokes": "https://youtu.be/1FASFr0mzxQ?si=rXrTVbpYWRMFXD7P",
    "tarak maheta": "https://www.youtube.com/watch?v=rwOF8PED29s&list=PL6Rtnh6YJK7YlxkEdFPuwx0FA_VvVciI1",
    "kirtidan gadhvi": "https://youtu.be/1_xiQP-aCig?si=nCEt_H9Mr-iFdck5",
    "arijit singh" : "https://youtu.be/00DvaPstcpo?si=UVz6wI7GmbILVMzI",
    "garba": "https://youtu.be/BPbbBR0X2GY?si=u1D0ggBdYTzI1c1N",
    "mataji aarti": "https://youtu.be/SU8aghkgeCQ?si=AJ-aVd4iTm8bLWVP",
    "ganpati bappa": "https://youtu.be/vcCL8RLz11k?si=KEomXtASko0ovcOJ",
    "jignesh dada": "https://youtu.be/9-uDAL7Dw3Y?si=9XzLL11mfmVMwPe1",
    "raj gadhvi": "https://youtu.be/qW1ss5bq90A?si=HUvToklpqMN1e3Mo"
}